Update ci .yml

diff --git a/.github/workflows/ci .yml b/.github/workflows/ci .yml
--- a/.github/workflows/ci .yml
+++ b/.github/workflows/ci .yml
@@ -1,5 +1,3 @@
-# .github/workflows/ci_cd.yml
-
 name: CI Pipeline
 
 on:
@@ -10,34 +8,41 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v3
-    - uses: actions/setup-python@v4
+    - name: Checkout Repository
+      uses: actions/checkout@v3
+
+    - name: Set up Python
+      uses: actions/setup-python@v4
       with:
         python-version: 3.11
-    - uses: iterative/setup-cml@v2
-    
+
+    - name: Set up CML
+      uses: iterative/setup-cml@v2
+
     - name: Install Dependencies
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
-    
+
     - name: Run main file
       run: |
-        python main.py
-    
+        python main.py || exit 1  # Exit with an error code if the script fails
+
     - name: Run Tests
       run: |
-        python -m unittest discover
+        python -m unittest discover || exit 1  # Exit with an error code if tests fail
 
     - name: Debug
       run: |
         ls -R
-    
+
     - name: Create CML report
       env:
         REPO_TOKEN: ${{ secrets.gfghdFGHDTGDbjvhd }}
       run: |
         echo "# First Line of our report" >> report.md
         echo "## Plots" >> report.md
-        echo "![Bar plot](\${GITHUB_WORKSPACE}/confusion_matrix_plot.png 'Bar plot')" >> report.md
-        cml publish report.md
+        echo "![Bar plot](${GITHUB_WORKSPACE}/confusion_matrix_plot.png 'Bar plot')" >> report.md
+
+        # Publish the CML report
+        cml publish report.md || exit 1  # Exit with an error code if report publishing fails
